site_name: Skapersøk docs
site_url: https://docs.skapersok.no

theme:
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode

extra_css:
  - stylesheet/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  - Getting Started:
      - Overview: getting_started/index.md
      - App Setup: getting_started/app_setup.md
      - Server Setup: getting_started/server_setup.md

  - The Skapersøk System:
      - Overview: system/index.md
      - Placement Codes: system/placement_codes.md
      - Grid System: system/grids.md

  - Usage:
      - Creating a new crate: usage/create_crate.md
      - Editing a crate: usage/edit_crate.md
      - Deleting a crate: usage/delete_crate.md
      - Generating labels: usage/generate_labels.md

  - Interfaces:
      - Search Page: interfaces/search_page.md
      - Admin panel: interfaces/admin_panel.md
      - Browse Page: interfaces/browse_page.md

  - Developer:
      - Overview: developer/index.md
      - API Reference: developer/APIReference.md
      - Database layout: developer/database_layout.md
      - Database setup: developer/database_setup.md
