site_name: Skapersøk docs
site_url: https://docs.skapersok.no

theme:
  name: material
  language: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode

extra_css:
  - stylesheet/extra.css

nav:
  - Home: index.md
  - Introduction: introduction.md

  - Getting Started:
      - Overview: getting_started/index.md
      - App Setup: getting_started/app_setup.md
      - Server Setup: getting_started/server_setup.md

  - The Skapersøk System:
      - Overview: system/index.md
      - Placement Codes: system/placement_codes.md
      - Grid System: system/grids.md

  - Usage:
      - Overview: usage/index.md
      - Backups: usage/backups.md
      - Join Links: usage/join_links.md

  - Developer:
      - Overview: developer/index.md
      - API Reference: developer/APIReference.md
      - Database layout: developer/database_layout.md
      - Database setup: developer/database_setup.md
